---

dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: molecule-vagrant-centos7-bento-{{cookiecutter.role_name|lower|replace(' ', '_') }}
    box: bento/centos-7
    memory: 512
    cpus: 1
  - name: molecule-vagrant-ubuntu-18.04-bento-{{cookiecutter.role_name|lower|replace(' ', '_') }}
    box: bento/ubuntu-18.04
    memory: 512
    cpus: 1
  - name: molecule-vagrant-archlinux-{{cookiecutter.role_name|lower|replace(' ', '_') }}
    box: archlinux/archlinux
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  # options:
  #   become: true
verifier:
  name: ansible
